### ISSUE TITLE
Create Base Chain

### ISSUE THREAD

**Issue by nphsu** [shunp/substrate_template#1]
以前にこちらをつくったのですが、練習を含めて新しくリポジトリを作成しました。
https://github.com/shunp/substrate_simple_sto
→古いバージョンです

似せてチェーンをつくりたいので、Substrateのテンプレートから余分な部分をのぞいて、シンプルなチェーンのみの実装をこちらにコミットしていただけますか？

**Comment by mitsu0925c74** [comment]
@shunp リポジトリ作成有難うございます。
substrateのテンプレートのシンプルなチェーンのみ、というのは、
collectable workshopで書いたdecl_module!,  decl_storage!のプログラムのことで合ってるでしょうか？
いまいちcollectable workshopでは、今自分が実装・実行しているのはカスタムなsubstrateなのか、nodeなのか、それともruntime moduleなのかが掴めなくて（苦笑）

**Comment by mitsu0925c74** [comment]
あ、以下のファイル群をコミットすればいいのか。

https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/build

あ、でもこれはnodeのtemplateか…。

**Comment by mitsu0925c74** [comment]
これをgitで落とし、コミットすればOKですか？（的外れだったらすみません笑）
https://github.com/paritytech/substrate-up

**Comment by nphsu** [comment]
素晴らしいです！！
チェーン動かして見たらちゃんと動いてますね！完璧です。

**Comment by nphsu** [comment]
1. コミットメッセージについて
これ参考になります！Issueとコミットが紐づきます。次回からのご参考に！
https://qiita.com/cotolier_risa/items/210db74e6496d4359be7

2. プロジェクト構成
ご相談なんですけど、こういう構成でつくっていくのはいかがですか？今回のチェーンとコントラクトをプロジェクト分けて、フロントのディレクトリと並列にする感じです。

```
|--/frontend
|--/basechain
|     |--/runtime
|     |--/src
|     |-- ...
|--/contracts
|     |-- ...
|--README.md
```

**Comment by mitsu0925c74** [comment]
1. これわかりやすい！参考にします。issueのcloseもできるんですね。

2. 賛成です。コミットしますね。
