### ISSUE TITLE
Create Base Frontend

### ISSUE THREAD

**Issue by nphsu** [shunp/substrate_template#3]
Frontendの骨格を作成する。
ベースはReact＋TypeScript

**Comment by mitsu0925c74** [comment]
TypeScript使うんですね！初めてです。

**Comment by nphsu** [comment]
はい、ベースできたら共有しますね！

**Comment by nphsu** [comment]
共通のリファレンス合った方が迷いが少ないと思うので、このプロジェクト参考にさせてもらいましょう。
https://github.com/akropolisio/erc20-substrate-bridge/tree/master/frontend

**Comment by mitsu0925c74** [comment]
承知しました！
